### ISSUE TITLE
make_raw_transaction (Transaction vs. PeercoinTx)

### ISSUE THREAD

**Issue by saeveritt** [PeerAssets/pypeerassets#122]
We need to pass network parameters to `make_raw_transaction` in `transactions.py` or choose between
Transaction and PeercoinTx appropriately.

Inside peerassets-btcpty transaction structs there are two classes, `Transaction` and `PeercoinTx`.
https://github.com/PeerAssets/pypeerassets/blob/master/pypeerassets/transactions.py#L66

**Comment by peerchemist** [comment]
This is relevant to new, unmerged branch @ belovachap:chapman_check_btcpy_integration

**Comment by saeveritt** [comment]
I believe it's relevant to both. Right now the master branch uses the `Transaction` class by default for `make_raw_transaction`.

**Comment by belovachap** [comment]
@saeveritt good catch, using the "experimental btcpy" (a.k.a. `PeerAssets/btcpy@master`) make_raw_transaction is hard coded to just use Bitcoin Transactions at the moment. I'll write a test and make a patch in https://github.com/PeerAssets/pypeerassets/pull/121 to either pass network params or otherwise let callers signal the Transaction Class they're working with :)

**Comment by peerchemist** [comment]
Network name parameter should be passed indeed.
